version: '3.7'

services:
  ssh:
    image: shellhub-ssh
    build:
      context: .
      dockerfile: ssh/Dockerfile
      target: development
    volumes:
      - ./ssh:/go/src/github.com/shellhub-io/shellhub/ssh
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
  api:
    image: shellhub-api
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
    volumes:
      - ./api:/go/src/github.com/shellhub-io/shellhub/api
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
  ui:
    image: shellhub-ui
    build:
      context: ui
      target: development
    volumes:
      - ./ui:/src
  gateway:
    image: shellhub-gateway
    build:
      context: gateway
    environment:
      - SHELLHUB_VERSION=latest
  agent:
    image: shellhub-agent
    build:
      context: .
      dockerfile: agent/Dockerfile
      target: development
      args:
        SHELLHUB_VERSION: latest
    privileged: true
    network_mode: host
    pid: host
    environment:
      - SERVER_ADDRESS=http://172.17.0.1
      - PRIVATE_KEY=/go/src/github.com/shellhub-io/shellhub/agent/shellhub.key
      - TENANT_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - SHELLHUB_VERSION=${SHELLHUB_VERSION}
    volumes:
      - ./agent:/go/src/github.com/shellhub-io/shellhub/agent
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
      - /:/host
    depends_on:
      - api
      - ssh
      - gateway
  register-srv:
    image: eduardoveiga/register-srv:test
    environment:
      - MONGO_HOST=mongo
    ports:
      - 8081:8081
    depends_on:
      - mongo
    links:
      - mongo
